--Tim Serio
--CSC 355 Section 602
--Assignment 4
--April 26, 2015


--1.
SELECT FNAME, LNAME FROM EMPLOYEE WHERE SUPERSSN IN
(SELECT SSN FROM EMPLOYEE WHERE FNAME = 'Janine' AND LNAME = 'Wallace');

--2.
SELECT WORKSON.ESSN FROM WORKSON 
INNER JOIN PROJECT ON WORKSON.PNO = PROJECT.PNUMBER
WHERE PROJECT.PLOCATION = 'Stafford' AND WORKSON.HOURS >= 10
GROUP BY WORKSON.ESSN;

--3.
SELECT AVG(SALARY) FROM DEPARTMENT 
INNER JOIN EMPLOYEE ON DEPARTMENT.DNUMBER = EMPLOYEE.DNO
WHERE DEPARTMENT.DNAME = 'Administration';

--4.
SELECT PROJECT.PNAME, SUM(WORKSON.HOURS) AS TOTALHRS FROM WORKSON 
INNER JOIN PROJECT ON WORKSON.PNO = PROJECT.PNUMBER 
GROUP BY PROJECT.PNAME 
ORDER BY TOTALHRS;

--5.
SELECT EMPLOYEE.LNAME, EMPLOYEE.SSN FROM EMPLOYEE 
LEFT JOIN WORKSON ON EMPLOYEE.SSN = WORKSON.ESSN
WHERE WORKSON.ESSN IS NULL;

--6.
SELECT EMPLOYEE.FNAME FROM EMPLOYEE
LEFT JOIN DEPENDENT ON EMPLOYEE.SSN = DEPENDENT.ESSN 
WHERE EMPLOYEE.DNO = 2
GROUP BY EMPLOYEE.FNAME
HAVING COUNT(DEPENDENT.DEPENDENTNAME) >= 1;

--7.
SELECT LNAME FROM EMPLOYEE WHERE SUPERSSN IN
(SELECT SSN FROM EMPLOYEE WHERE SUPERSSN = 121231234)
ORDER BY LNAME;


--8.
SELECT DNO, COUNT(SSN) AS NUMEMP, AVG(SALARY) AS AVGSALRY FROM EMPLOYEE
GROUP BY DNO
HAVING AVG(SALARY) < 50000;